/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as NosotrasRouteImport } from './routes/nosotras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios/index'
import { Route as ServiciosPedicureRouteImport } from './routes/servicios/pedicure'
import { Route as ServiciosManicureRouteImport } from './routes/servicios/manicure'
import { Route as ServiciosEsteticaRouteImport } from './routes/servicios/estetica'
import { Route as ServiciosCabelloRouteImport } from './routes/servicios/cabello'
import { Route as ServiciosCabinasIndexRouteImport } from './routes/servicios/cabinas/index'
import { Route as ServiciosCabinasSlugRouteImport } from './routes/servicios/cabinas/$slug'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrasRoute = NosotrasRouteImport.update({
  id: '/nosotras',
  path: '/nosotras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPedicureRoute = ServiciosPedicureRouteImport.update({
  id: '/servicios/pedicure',
  path: '/servicios/pedicure',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosManicureRoute = ServiciosManicureRouteImport.update({
  id: '/servicios/manicure',
  path: '/servicios/manicure',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosEsteticaRoute = ServiciosEsteticaRouteImport.update({
  id: '/servicios/estetica',
  path: '/servicios/estetica',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCabelloRoute = ServiciosCabelloRouteImport.update({
  id: '/servicios/cabello',
  path: '/servicios/cabello',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCabinasIndexRoute = ServiciosCabinasIndexRouteImport.update({
  id: '/servicios/cabinas/',
  path: '/servicios/cabinas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCabinasSlugRoute = ServiciosCabinasSlugRouteImport.update({
  id: '/servicios/cabinas/$slug',
  path: '/servicios/cabinas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotras': typeof NosotrasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
  '/servicios/cabello': typeof ServiciosCabelloRoute
  '/servicios/estetica': typeof ServiciosEsteticaRoute
  '/servicios/manicure': typeof ServiciosManicureRoute
  '/servicios/pedicure': typeof ServiciosPedicureRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/servicios/cabinas/$slug': typeof ServiciosCabinasSlugRoute
  '/servicios/cabinas/': typeof ServiciosCabinasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotras': typeof NosotrasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
  '/servicios/cabello': typeof ServiciosCabelloRoute
  '/servicios/estetica': typeof ServiciosEsteticaRoute
  '/servicios/manicure': typeof ServiciosManicureRoute
  '/servicios/pedicure': typeof ServiciosPedicureRoute
  '/servicios': typeof ServiciosIndexRoute
  '/servicios/cabinas/$slug': typeof ServiciosCabinasSlugRoute
  '/servicios/cabinas': typeof ServiciosCabinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotras': typeof NosotrasRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tienda': typeof TiendaRoute
  '/servicios/cabello': typeof ServiciosCabelloRoute
  '/servicios/estetica': typeof ServiciosEsteticaRoute
  '/servicios/manicure': typeof ServiciosManicureRoute
  '/servicios/pedicure': typeof ServiciosPedicureRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/servicios/cabinas/$slug': typeof ServiciosCabinasSlugRoute
  '/servicios/cabinas/': typeof ServiciosCabinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacto'
    | '/galeria'
    | '/login'
    | '/nosotras'
    | '/sobre-nosotros'
    | '/tienda'
    | '/servicios/cabello'
    | '/servicios/estetica'
    | '/servicios/manicure'
    | '/servicios/pedicure'
    | '/servicios/'
    | '/servicios/cabinas/$slug'
    | '/servicios/cabinas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contacto'
    | '/galeria'
    | '/login'
    | '/nosotras'
    | '/sobre-nosotros'
    | '/tienda'
    | '/servicios/cabello'
    | '/servicios/estetica'
    | '/servicios/manicure'
    | '/servicios/pedicure'
    | '/servicios'
    | '/servicios/cabinas/$slug'
    | '/servicios/cabinas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacto'
    | '/galeria'
    | '/login'
    | '/nosotras'
    | '/sobre-nosotros'
    | '/tienda'
    | '/servicios/cabello'
    | '/servicios/estetica'
    | '/servicios/manicure'
    | '/servicios/pedicure'
    | '/servicios/'
    | '/servicios/cabinas/$slug'
    | '/servicios/cabinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  NosotrasRoute: typeof NosotrasRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TiendaRoute: typeof TiendaRoute
  ServiciosCabelloRoute: typeof ServiciosCabelloRoute
  ServiciosEsteticaRoute: typeof ServiciosEsteticaRoute
  ServiciosManicureRoute: typeof ServiciosManicureRoute
  ServiciosPedicureRoute: typeof ServiciosPedicureRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
  ServiciosCabinasSlugRoute: typeof ServiciosCabinasSlugRoute
  ServiciosCabinasIndexRoute: typeof ServiciosCabinasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotras': {
      id: '/nosotras'
      path: '/nosotras'
      fullPath: '/nosotras'
      preLoaderRoute: typeof NosotrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/pedicure': {
      id: '/servicios/pedicure'
      path: '/servicios/pedicure'
      fullPath: '/servicios/pedicure'
      preLoaderRoute: typeof ServiciosPedicureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/manicure': {
      id: '/servicios/manicure'
      path: '/servicios/manicure'
      fullPath: '/servicios/manicure'
      preLoaderRoute: typeof ServiciosManicureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/estetica': {
      id: '/servicios/estetica'
      path: '/servicios/estetica'
      fullPath: '/servicios/estetica'
      preLoaderRoute: typeof ServiciosEsteticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cabello': {
      id: '/servicios/cabello'
      path: '/servicios/cabello'
      fullPath: '/servicios/cabello'
      preLoaderRoute: typeof ServiciosCabelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cabinas/': {
      id: '/servicios/cabinas/'
      path: '/servicios/cabinas'
      fullPath: '/servicios/cabinas/'
      preLoaderRoute: typeof ServiciosCabinasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cabinas/$slug': {
      id: '/servicios/cabinas/$slug'
      path: '/servicios/cabinas/$slug'
      fullPath: '/servicios/cabinas/$slug'
      preLoaderRoute: typeof ServiciosCabinasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  NosotrasRoute: NosotrasRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TiendaRoute: TiendaRoute,
  ServiciosCabelloRoute: ServiciosCabelloRoute,
  ServiciosEsteticaRoute: ServiciosEsteticaRoute,
  ServiciosManicureRoute: ServiciosManicureRoute,
  ServiciosPedicureRoute: ServiciosPedicureRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
  ServiciosCabinasSlugRoute: ServiciosCabinasSlugRoute,
  ServiciosCabinasIndexRoute: ServiciosCabinasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
